### PR TITLE
allow command-line modification of RPATH (via CMAKE_INSTALL_RPATH)

### PR DESCRIPTION
**Pull request by elrond79**
Without this, there is no way to modify the RPATH of the output binaries, without modifying the source, as CMAKE_INSTALL_RPATH was always unconditionally overridden. This change will make it easier for third parties to build the plugin for the particular needs of their studio.

Note - if using this, I recommend also passing these to cmake:

    -D CMAKE_EXE_LINKER_FLAGS=-Wl,--enable-new-dtags
    -D CMAKE_SHARED_LINKER_FLAGS=-Wl,--enable-new-dtags

...as this will make the resultant binary use RUNPATH, not RPATH, which is overridable by LD_LIBRARY_PATH.

### CODE REVIEW

**Comment by fabal** [comment]
Hi @elrond79 
there's no way to modify the RPATH because AL_USDMaya does not officially support it. Adding this modification would open a door that we'd like to keep closed for now.
What's the particular need of your studio in this case?
FYI it's possible to change RPATH/RUNPATH in binaries using `chrpath`. If you're running automated deployment scripts, you could easily modify RPATHs on the fly if needed.

**Comment by elrond79** [comment]
I think this probably boils down to the fact that we prefer using RUNPATH to control dynamic linking over LD_LIBRARY_PATH, and I'm guessing you folks prefer the opposite.

We could get into a discussion of the relative merits of both approaches, but I think the more important point is that different studios / end users are going to have different views on this point. By not supporting changing of RPATH/RUNPATH, AL is sort of just making life harder for any studios which don't have the same viewpoint.

On the other hand, this patch should make it easier for studios preferring to use RUNPATH, without making things more difficult for any other studios which prefer using LD_LIBRARY_PATH.  This simply allows explicit passing in of a cmake variable (an environment variable shouldn't have any effect), so by just not passing that into the build command, you folks should be unchanged.  Unless I'm missing something?

**Comment by fabal** [comment]
There's certainly no RUNPATH discrimination being made here, both options (LD_LIBRARY_PATH/RUNPATH) are valid. It's more a matter of what's "officially" supported.
One compromise would be to modify the configuration to build AL_USDMaya _optionally_ baking the paths in RUNPATH without relying on CMAKE_INSTALL_PREFIX (which then could be used from the command line). This would satisfy both parties:

- AL_USDMaya is built out of the box with everything needed baked in RUNPATH (the "official" way)
- clients may disable this option and configure it from the command line to suit their needs

What do you think?

**Comment by elrond79** [comment]
Wait... I think perhaps there might be some misunderstanding here.  Our PR would always bake in your standard values to the RPATH / RUNPATH - it would simply allow (optional) prepending of additional values.  So it should always work out of the box, you can just add in some more stuff if you desire.

Or, I could be not quite following what you were proposing.  It sounded like you were proposing adding some new option, say, AL_STANDARD_RPATH, which would default to true... and you could then disable, like this:

-DAL_STANDARD_RPATH=FALSE -DCMAKE_INSTALL_RPATH=/some/other/paths:/more/paths

Is that sort of what you had in mind?

**Pull request merged**
