### PR TITLE
Updating AL_USDMaya to work with usd-0.19.1

### PR DESCRIPTION
**Pull request by sirpalee**
## Description (this won't be part of the changelog)
The following PR updates the plugin to work with the latest changes found on the dev branch. The changes won't build, because of UsdImagingGLEngine::TestIntersectionBatch was removed, without any alternative. For now, I left that piece of code unchanged.

> Use Markdown list syntax for each entry.

> Filled out fields will be added to the changelog.

### Added
Added support for 0.19.1 version of USD.
### Removed
Removed support for 0.18.11 version of USD.
## Checklist (Please do not remove this line)
- [x] Make sure the Title and Description of the PR make sense and  provide sufficient context for your work
- [x] Do any added files have the correct AL Apache Licence Header?
- [x] Are there Doxygen comments in the headers?
- [x] Are any new features, behaviour changes documented in the .md format [documentation](https://github.com/AnimalLogic/AL_USDMaya/docs)?
- [x] Have you added, updated tests to cover new features and behaviour changes?
- [x] Have you filled out at least one changelog entry?

### CODE REVIEW

**Comment by sirpalee** [comment]
Added a quick take on subclassing UsdImagingGLEngine as discussed in # 133. It's not tested, formatted or has its functions exported properly for now.

**Comment by sirpalee** [comment]
Updated formatting to match the rest of the codebase and ran some tests. Everything works as expected.

I'm not sure about the best place for "Engine", for now, I put it into the nodes subfolder since it's not really used anywhere else. Also, since it contains code copied directly from UsdImagingGL, should I add the Pixar copyright headers to Engine.cpp?

**Comment by murphyeoin** [comment]
@sirpalee thanks for all of your hard work here, we're a bit tardy on approvals at the moment (I'm going to blame  Australian summer holidays), we're waiting to have our own 19.01 build working internally to allow us to test this..

**Comment by fabal** [comment]
Thanks @sirpalee , just two things:
* could you keep only changes related to this PR and remove other ones?
* would you mind changing the base branch from `master` to `develop`?
Once done, we are now ready to merge your work.

**Comment by sirpalee** [comment]
@fabal Rebased! Now it should only contain changes that are required to make AL_USDMaya compatible with usd-0.19.1.

**Comment by fabal** [comment]
Awesome, thanks.

**Comment by elrond79** [comment]
Cleaned up the commit history a bit and rebased, if you haven't already merged this...

**Review by fabal — APPROVED** [review]

**Comment by b0ssi** [comment]
Thanks @elrond79, we will be merging this shortly.

**Pull request merged**
