### PR TITLE
remove the reliance on pxrConfig.cmake, and instead use FindUSD

### PR DESCRIPTION
**Pull request by elrond79**
This is more conventional than pointing to pxrConfig.cmake, doesn't not need an source-directory of USD at AL_USDMaya build time, and greatly reduces the need for files copy-and-pasted from the USD project (as evidenced by the large number of cmake files where are removed in this branch).

### CODE REVIEW

**Comment by fabal** [comment]
Hi @elrond79 
`pxrConfig.cmake` configures cmake using so-called **imported targets** which are a "modern" way of dealing with dependencies in cmake. These targets are self-contained (i.e include and library paths, requirements to other targets). The use of a `find_package(USD)` is definitely a good idea. Could be used to discover and include `pxrConfig.cmake`.
Regarding Qt, the good news is that this requirement is going to be removed soon!

**Comment by chadrik** [comment]
related issue:  https://github.com/PixarAnimationStudios/USD/issues/284

**Comment by elrond79** [comment]
Putting this on hold for now, pending resolution of USD issue chad linked (https://github.com/PixarAnimationStudios/USD/issues/284)

**Comment by elrond79** [comment]
Changed the way we do our build to still use pxrConfig, and it's imported targets, and then broke out the remaining changes into 3 separate PRs (since they actually end up being totally independent of each other):

https://github.com/AnimalLogic/AL_USDMaya/pull/57
https://github.com/AnimalLogic/AL_USDMaya/pull/58
https://github.com/AnimalLogic/AL_USDMaya/pull/59

**Pull request closed without merging**
