### PR TITLE
Removing incorrect logger call.

### PR DESCRIPTION
**Pull request by elrond79**
Fixes a crash due to an incorrect logger call.

### CODE REVIEW

**Comment by chadrik** [comment]
@sirpalee the AL folks have a question for you on this.

**Comment by murphyeoin** [comment]
Hello @sirpalee just wondering what the crash is and when it occurs etc? Any more info would be great Thanks
Eoin

**Comment by sirpalee** [comment]
@murphyeoin I'll dig up our internal ticket and try to remember what was happening. We needed this fix for an older version, it's also possible that it has been fixed since then.

I remember something being messed up in the logger and the clear function created a sigsegv because of some incorrect stack setup or something.

**Comment by murphyeoin** [comment]
Hello @sirpalee - whenever you have time, that would be great.. All things remaining equal, we'd like to keep that logger call in place, so would prefer to fix the problem if possible at root..

**Comment by sirpalee** [comment]
I dug around our internal tracker and tried to reproduce the issue, but things seemed to work. We'll remove the change from our branch, and close down the ticket unless we run into the problem again. This time we'll have enough time for a proper solution and not just a bandaid to get things running.

**Pull request closed without merging**
