### PR TITLE
consolidate MayaReference update logic to make it more resilient

### PR DESCRIPTION
**Pull request by nxkb**
## Description
Combine the similar logic from update() and LoadMayaReference() to make the maya reference translator more resilient to imported references and stage changes.

The main change is just a reordering of the logic. I consolidated the logic for finding the reference node into update() and only call "LoadMayaReference" if we need to create a fresh reference. update() becomes the main entry point for initial creation and updating and holds all the logic for what to do. I didn't see any good reason for the code paths to be different and it meant that some situations were not handled in one versus the other.

### Fixed
- If multiple object changed notices pile up for a maya reference prim instead of bringing in the reference multiple times, it will only bring it in once.
- If a reference is imported, the proxy shape will bring in a fresh reference the next time the proxy shape is resynced if the prim is still active. (This is especially desirable for our asset manager which we use to bring in references. If an artist imports a ref, it "severs" the connection to the stage and a new reference is brought in if requested) 

## Checklist (Please do not remove this line)
- [x] Make sure the Title and Description of the PR make sense and  provide sufficient context for your work
- [x] Do any added files have the correct AL Apache Licence Header?
- [x] Are there Doxygen comments in the headers?
- [x] Are any new features, behaviour changes documented in the .md format [documentation](https://github.com/AnimalLogic/AL_USDMaya/docs)?
- [x] Have you added, updated tests to cover new features and behaviour changes?
- [x] Have you filled out at least one changelog entry?

### CODE REVIEW

**Review by robthebloke — APPROVED** [review]
lgtm

**Comment by b0ssi** [comment]
Hi @nxkb - some tests are failing for us when we run against develop - can you please confirm whether everything is passing for you or not? Cheers!

**Comment by murphyeoin** [comment]
@nxkb here is our test output
```
/scratch/dev/AL_USDMaya/src/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ActiveInactive.cpp:732: Failure
Value of: bool(sl.add("fred:pCube1"))
  Actual: false
Expected: true
/scratch/dev/AL_USDMaya/src/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ActiveInactive.cpp:743: Failure
Value of: bool(sl.add("fred:pCube1"))
  Actual: false
Expected: true
File read in  0.0092 seconds.
File read in  0.0092 seconds.
/scratch/dev/AL_USDMaya/src/plugin/AL_USDMayaTestPlugin/AL/usdmaya/nodes/test_ActiveInactive.cpp:746: Failure
Value of: bool(sl.add("fred1:pCube1"))
  Actual: false
Expected: true
```
Digest:
```
19:16:51 [AL_USDMaya] [  FAILED  ] 1 test, listed below:
19:16:51 [AL_USDMaya] [  FAILED  ] ActiveInactive.disable
19:16:51 [AL_USDMaya] 
19:16:51 [AL_USDMaya]  1 FAILED TEST
19:16:51 [AL_USDMaya]                __
19:16:51 [AL_USDMaya]               /x_)
19:16:51 [AL_USDMaya]      _/\/\/\_/ /
19:16:51 [AL_USDMaya]    _|         /
19:16:51 [AL_USDMaya]  _|  (  | (  |
19:16:51 [AL_USDMaya] /__.-'|_|--|_|

```

**Comment by elrond79** [comment]
Ah, our mistake - this test made use of another internal modification we've made (adding a "pauseUpdates" attribute), which isn't part of this PR.

We'll modify the test to not use that...

**Comment by murphyeoin** [comment]
thanks @elrond79

**Comment by nxkb** [comment]
hi @murphyeoin, I've updated the tests so they should be passing on develop again!

**Pull request merged**
