### PR TITLE
(Re-Created) Change transform translation to use PxrUsdMayaXformStack, the same object used in usd plugin

### PR DESCRIPTION
**Pull request by dbaz**
"This is more flexible than the existing method, giving better-aligned axes / manipulators in many situations, particularly as more xforms ops are added, and deals smoothly with switching between a single pivot ("pivot") and dual pivots ("rotatePivot" / "scalePivot")."

Note:
We pulled out this branch as we have some trouble merging our internal source with the external, I created this branches PR so we can merge it again once we sort out the issue.

originally from https://github.com/AnimalLogic/AL_USDMaya/pull/43

### CODE REVIEW

**Comment by elrond79** [comment]
Merged in latest develop, and fixed merge conflicts...

**Comment by dbaz** [comment]
The code is good, we are just sorting things out with the reliance on the pixar's usdMaya plugin internally

**Comment by elrond79** [comment]
merged in latest develop

**Comment by elrond79** [comment]
Closing this for now, as it seems we're blocked on the linking-against-usdMaya issue.

At some point in the future, I may try to move the xformStack stuff into "main" usd (as there's not really anything in the base classes that's maya specific, and the "concept" is generally useful), or else wait until usdMaya / AL_USDMaya are unified somehow.

**Comment by elrond79** [comment]
Oops - realized I can't close, as I no longer created this PR!

**Comment by dbaz** [comment]
Ah yes. Closed.

**Pull request closed without merging**
